# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false


security.oauth2.jwt.key: 494847a9c8a147bf82f4ca6da59efe61


# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false


vidada:
    debug.enabled: false
    metadata.fileAttributes.enabled: true
    thumbnails:
        maxWidth: 500
        aspectRatio: 0.7

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

spring:
    messageSource:
        cacheSeconds: 1

    jpa.properties:
        jadira.usertype.autoRegisterUserTypes: true
        jadira.usertype.databaseZone: UTC
        jadira.usertype.javaZone: UTC


swagger:
    title: vidada API
    description: vidada applications and beyond!
    termsOfServiceUrl: http://jhipster.github.io/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html

